source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.4'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rails', '~> 6.1.6', '>= 6.1.6.1'

gem 'bootsnap', '>= 1.4.4', require: false
# cors
gem 'rack-cors'
# jwt
gem 'jwt'
# aws-sdk
gem 'aws-sdk'
# json_serializer
gem 'jsonapi-serializer'
# API連携
gem 'faraday'
gem 'faraday_middleware'
# OGP画像取得
gem 'link_thumbnailer'
# scraping
gem 'nokogiri'
# 定期実行
gem 'whenever'

group :development, :test do
  # デバッグ用
  gem 'bullet'
  gem 'pry-byebug'
  gem 'pry-rails'

  # RSpec関係用
  gem "factory_bot_rails"
  gem "rspec-rails"
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'

  # デバッグ用
  gem 'better_errors'
  gem 'binding_of_caller'

  # フォーマッタ用
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubocop-rubycw'

  # モデルのスキーマ情報を見やすく
  gem 'annotate'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# 日本語化
gem 'enum_help'
gem 'rails-i18n'

# seedファイル
gem 'seed-fu'
